//! xtask — developer commands for the stave workspace.
//!
//! Run via `cargo xtask <command>`. The companion `[alias] xtask = "run -p xtask --"`
//! lives in `.cargo/config.toml`.
//!
//! Commands (filled in by follow-on tickets):
//!   * `sync-spec`  — fetch the live OpenAPI spec, write to spec/, update sha256
//!   * `regen`      — run progenitor against vendored spec, write stave-api
//!   * `diff-spec`  — compare local vendored spec vs upstream, summarize ops added/removed/changed

use std::{fs, path::PathBuf, sync::OnceLock};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use regex::Regex;
use sha2::{Digest, Sha256};

const SPEC_URL: &str = "https://docs.iru.com/openapi/iru-endpoint-openapi.json";
const SPEC_REL_PATH: &str = "spec/iru-endpoint-openapi.json";
const SPEC_SHA_REL_PATH: &str = "spec/iru-endpoint-openapi.json.sha256";

/// Sanitization rules: every regex match is replaced by its placeholder
/// before the spec lands on disk. Source code stores patterns, not
/// literal secrets — both because GitHub push protection scans this
/// file too, and because a literal-needle approach can't catch new
/// secret-shaped examples that share a pattern.
///
/// Add a rule here when `sync-spec` surfaces a new pattern. Do not
/// add an `--allow-secrets` flag to bypass.
struct SanitizeRule {
    pattern: &'static str,
    replacement: &'static str,
    description: &'static str,
}

const SANITIZE_RULES: &[SanitizeRule] = &[SanitizeRule {
    pattern: r"https://hooks\.slack\.com/services/[A-Za-z0-9_-]+/[A-Za-z0-9_-]+/[A-Za-z0-9_-]+",
    replacement: "https://hooks.slack.com/services/SLACK-TEAM-EXAMPLE/SLACK-BOT-EXAMPLE/SLACK-WEBHOOK-EXAMPLE",
    description: "Slack incoming-webhook URL",
}];

fn compiled_rules() -> &'static [(Regex, &'static str, &'static str)] {
    static RULES: OnceLock<Vec<(Regex, &'static str, &'static str)>> = OnceLock::new();
    RULES.get_or_init(|| {
        SANITIZE_RULES
            .iter()
            .map(|r| {
                (
                    Regex::new(r.pattern).expect("sanitize rule regex"),
                    r.replacement,
                    r.description,
                )
            })
            .collect()
    })
}

#[derive(Parser, Debug)]
#[command(name = "xtask", about = "Developer tasks for stave")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand, Debug)]
enum Cmd {
    /// Fetch the upstream OpenAPI spec and update the vendored copy.
    SyncSpec,
    /// Regenerate stave-api from the vendored spec. Not yet implemented.
    Regen,
    /// Diff the vendored spec against upstream. Not yet implemented.
    DiffSpec,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.cmd {
        Cmd::SyncSpec => sync_spec(),
        Cmd::Regen => regen(),
        Cmd::DiffSpec => {
            anyhow::bail!("xtask diff-spec: not yet implemented (follow-on ticket)");
        }
    }
}

const GENERATED_REL_PATH: &str = "crates/stave-api/src/generated.rs";

fn regen() -> Result<()> {
    let workspace_root = workspace_root()?;
    let spec_path = workspace_root.join(SPEC_REL_PATH);
    let out_path = workspace_root.join(GENERATED_REL_PATH);

    eprintln!("xtask: reading spec {}", spec_path.display());
    let spec_text =
        fs::read_to_string(&spec_path).with_context(|| format!("read {}", spec_path.display()))?;
    let mut spec: openapiv3::OpenAPI =
        serde_json::from_str(&spec_text).context("parse spec as OpenAPI v3")?;

    let stripped_multipart = strip_multipart_request_bodies(&mut spec);
    if stripped_multipart > 0 {
        eprintln!(
            "xtask: stripped {stripped_multipart} multipart/form-data request bod(ies) \
             (progenitor cannot represent them; upload endpoints keep their metadata \
             but lose the typed body in the generated client)"
        );
    }

    let collapsed_success = collapse_multi_responses(&mut spec, ResponseClass::Success);
    let collapsed_error = collapse_multi_responses(&mut spec, ResponseClass::Error);
    if collapsed_success + collapsed_error > 0 {
        eprintln!(
            "xtask: collapsed {collapsed_success} multi-success and {collapsed_error} multi-error response(s) (progenitor requires at most one body per class)"
        );
    }

    eprintln!("xtask: generating client");
    let mut generator = progenitor::Generator::default();
    let tokens = generator
        .generate_tokens(&spec)
        .map_err(|e| anyhow::anyhow!("progenitor generate_tokens: {e}"))?;
    let ast = syn::parse2(tokens).context("parse generated tokens as syn AST")?;
    let body = prettyplease::unparse(&ast);

    let banner = "// Generated by `cargo xtask regen` from spec/iru-endpoint-openapi.json.\n\
                  // DO NOT EDIT BY HAND. Re-run regen to refresh.\n\
                  #![allow(unused_imports, dead_code, clippy::all)]\n\n";
    let mut content = String::with_capacity(banner.len() + body.len());
    content.push_str(banner);
    content.push_str(&body);

    fs::write(&out_path, content.as_bytes())
        .with_context(|| format!("write {}", out_path.display()))?;
    eprintln!(
        "xtask: wrote {} ({} bytes)",
        out_path.display(),
        content.len()
    );
    Ok(())
}

fn sync_spec() -> Result<()> {
    let workspace_root = workspace_root()?;
    let spec_path = workspace_root.join(SPEC_REL_PATH);
    let sha_path = workspace_root.join(SPEC_SHA_REL_PATH);

    eprintln!("xtask: fetching spec from {SPEC_URL}");
    let body = reqwest::blocking::get(SPEC_URL)
        .context("fetch spec")?
        .error_for_status()
        .context("spec endpoint returned non-2xx")?
        .text()
        .context("read spec body")?;

    let (sanitized, applied) = sanitize(&body);
    if applied > 0 {
        eprintln!("xtask: sanitized {applied} secret-shaped example(s) before writing");
    }

    // Synthesize missing operationIds in the vendored copy. Keeps the spec
    // self-contained: progenitor and the SDK both read the same file with
    // every operation named. Round-trips through openapiv3 to apply the
    // mutation, then re-serializes to YAML.
    let normalized = normalize_with_synthesized_ids(&sanitized)?;

    fs::create_dir_all(spec_path.parent().expect("spec/ parent"))?;
    fs::write(&spec_path, normalized.as_bytes())
        .with_context(|| format!("write {}", spec_path.display()))?;

    let body = normalized.as_bytes();
    let mut hasher = Sha256::new();
    hasher.update(body);
    let digest = hex::encode(hasher.finalize());
    fs::write(&sha_path, format!("{digest}  iru-endpoint-openapi.json\n"))
        .with_context(|| format!("write {}", sha_path.display()))?;

    eprintln!(
        "xtask: wrote {} ({} bytes)",
        spec_path.display(),
        body.len()
    );
    eprintln!("xtask: sha256 {digest}");
    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    // CARGO_MANIFEST_DIR points at xtask/; one level up is the workspace root.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR unset")?;
    Ok(PathBuf::from(manifest_dir)
        .parent()
        .context("xtask has no parent dir")?
        .to_path_buf())
}

/// Round-trip the sanitized spec through openapiv3 to assign a
/// deterministic operationId to every operation that lacks one, then
/// re-serialize back to YAML. Lets the vendored on-disk file act as
/// the single source of truth: every operation is reachable by ID
/// from both progenitor (via xtask regen) and the SDK registry (which
/// reads the same file at runtime).
fn normalize_with_synthesized_ids(json: &str) -> Result<String> {
    let mut spec: openapiv3::OpenAPI =
        serde_json::from_str(json).context("parse spec as OpenAPI v3")?;
    let synthesized = fill_missing_operation_ids(&mut spec);
    if synthesized > 0 {
        eprintln!("xtask: synthesized {synthesized} operationId(s) into vendored spec");
    }
    serde_json::to_string_pretty(&spec).context("re-serialize spec to JSON")
}

/// Walk every operation in the spec and assign a deterministic
/// operationId to any that lacks one. progenitor requires every
/// operation to have an ID; iru's spec carries none at all, so we
/// derive `{method}_{path-with-params-stripped}` (with the `/api/vN`
/// prefix removed) as a stable fallback.
fn fill_missing_operation_ids(spec: &mut openapiv3::OpenAPI) -> usize {
    let mut count = 0;
    for (path, path_item) in spec.paths.paths.iter_mut() {
        let openapiv3::ReferenceOr::Item(item) = path_item else {
            continue;
        };
        for (method, op) in operations_mut(item) {
            if op.operation_id.is_none() {
                op.operation_id = Some(synthesize_operation_id(method, path));
                count += 1;
            }
        }
    }
    count
}

fn operations_mut(
    item: &mut openapiv3::PathItem,
) -> Vec<(&'static str, &mut openapiv3::Operation)> {
    let mut out: Vec<(&'static str, &mut openapiv3::Operation)> = Vec::new();
    if let Some(op) = &mut item.get {
        out.push(("get", op));
    }
    if let Some(op) = &mut item.put {
        out.push(("put", op));
    }
    if let Some(op) = &mut item.post {
        out.push(("post", op));
    }
    if let Some(op) = &mut item.delete {
        out.push(("delete", op));
    }
    if let Some(op) = &mut item.options {
        out.push(("options", op));
    }
    if let Some(op) = &mut item.head {
        out.push(("head", op));
    }
    if let Some(op) = &mut item.patch {
        out.push(("patch", op));
    }
    if let Some(op) = &mut item.trace {
        out.push(("trace", op));
    }
    out
}

/// progenitor rejects `multipart/form-data` request bodies outright
/// ("unexpected content type"). The iru spec uses them on the library
/// upload endpoints (custom apps, in-house apps). This pre-pass removes
/// the request body from those operations *in the in-memory model only*
/// — the vendored spec keeps them, and the SDK's spec-driven dispatch
/// still sees `has_body`. Real multipart uploads are out of scope for
/// the generated client; a curated upload verb is the eventual home
/// for that flow.
fn strip_multipart_request_bodies(spec: &mut openapiv3::OpenAPI) -> usize {
    let mut stripped = 0;
    for (_path, path_item) in spec.paths.paths.iter_mut() {
        let openapiv3::ReferenceOr::Item(item) = path_item else {
            continue;
        };
        for (_method, op) in operations_mut(item) {
            let has_multipart = matches!(
                &op.request_body,
                Some(openapiv3::ReferenceOr::Item(rb))
                    if rb.content.keys().any(|k| k.starts_with("multipart/"))
            );
            if has_multipart {
                op.request_body = None;
                stripped += 1;
            }
        }
    }
    stripped
}

#[derive(Clone, Copy)]
enum ResponseClass {
    Success,
    Error,
}

/// progenitor extracts the success and error response groups separately
/// (`is_success_or_default`, `is_error_or_default`) and asserts each
/// group's distinct Rust type count is `<= 1`. Type comes from response
/// content: an `application/json`-with-schema is a typed body, any other
/// content is `Raw`, no content is `None`. So an op with `200 {body}` +
/// `204` already trips the assertion (`Type(X)` vs `None`), even though
/// we humans read it as fine.
///
/// To accommodate specs with multiple bodied responses per class we collapse each class to a
/// single response per operation. Preference: bodied responses beat
/// unbodied; within bodied, lowest specific code beats Range/Default.
/// Dropped responses lose their schema in the generated client; CLI
/// verbs that need richer multi-status handling can read raw responses.
fn collapse_multi_responses(spec: &mut openapiv3::OpenAPI, class: ResponseClass) -> usize {
    use openapiv3::StatusCode;
    let mut collapsed = 0;
    for (_path, path_item) in spec.paths.paths.iter_mut() {
        let openapiv3::ReferenceOr::Item(item) = path_item else {
            continue;
        };
        for (_method, op) in operations_mut(item) {
            // (score, status_clone) — lower score = preferred to keep.
            let mut candidates: Vec<(u64, StatusCode)> = op
                .responses
                .responses
                .iter()
                .filter_map(|(status, resp)| {
                    let openapiv3::ReferenceOr::Item(r) = resp else {
                        return None;
                    };
                    response_score(status, class, !r.content.is_empty())
                        .map(|s| (s, status.clone()))
                })
                .collect();
            // openapiv3 represents the default response as a sibling field,
            // not a key in `responses`. Both classes' filters include it.
            let default_in_class = matches!(class, ResponseClass::Success | ResponseClass::Error);
            if default_in_class {
                if let Some(d) = op.responses.default.as_ref() {
                    let bodied = match d {
                        openapiv3::ReferenceOr::Item(r) => !r.content.is_empty(),
                        _ => false,
                    };
                    candidates.push((default_score(class, bodied), StatusCode::Range(0)));
                }
            }

            if candidates.len() <= 1 {
                continue;
            }

            candidates.sort_by_key(|(s, _)| *s);
            for (_score, status) in candidates.into_iter().skip(1) {
                match status {
                    StatusCode::Range(0) => {
                        // Sentinel for "default" — survives only one pass.
                        op.responses.default = None;
                    }
                    other => {
                        op.responses.responses.shift_remove(&other);
                    }
                }
                collapsed += 1;
            }
        }
    }
    collapsed
}

/// Score a status against a class. Lower = preferred. `None` means the
/// status is not in the class. Bodied entries always sort below unbodied;
/// within a tier, lower codes sort first; Range/Default fall last.
fn response_score(
    status: &openapiv3::StatusCode,
    class: ResponseClass,
    has_body: bool,
) -> Option<u64> {
    use openapiv3::StatusCode;
    let code: u64 = match (status, class) {
        (StatusCode::Code(c), ResponseClass::Success) if (200..=299).contains(c) => *c as u64,
        (StatusCode::Code(101), ResponseClass::Success) => 101,
        (StatusCode::Range(2), ResponseClass::Success) => 2_999,
        (StatusCode::Code(c), ResponseClass::Error) if (400..=599).contains(c) => *c as u64,
        (StatusCode::Range(4), ResponseClass::Error) => 4_999,
        (StatusCode::Range(5), ResponseClass::Error) => 5_999,
        _ => return None,
    };
    Some(if has_body { code } else { code + 1_000_000 })
}

fn default_score(class: ResponseClass, has_body: bool) -> u64 {
    let _ = class;
    let base: u64 = 999_999; // worse than any explicit Range
    if has_body { base } else { base + 1_000_000 }
}

fn synthesize_operation_id(method: &str, path: &str) -> String {
    // Strip the constant `/api/vN` prefix so ids read as
    // `get_devices`, not `get_api_v1_devices`. Non-prefixed paths
    // (if the vendor ever adds any) pass through unchanged.
    static PREFIX: OnceLock<Regex> = OnceLock::new();
    let prefix = PREFIX.get_or_init(|| Regex::new(r"^/api/v\d+").expect("prefix regex"));
    let path = prefix.replace(path, "");
    let mut id = String::with_capacity(method.len() + path.len());
    id.push_str(method);
    for ch in path.chars() {
        match ch {
            '/' | '-' => id.push('_'),
            '{' | '}' => {}
            c if c.is_ascii_alphanumeric() => id.push(c.to_ascii_lowercase()),
            _ => id.push('_'),
        }
    }
    while id.contains("__") {
        id = id.replace("__", "_");
    }
    id.trim_end_matches('_').to_string()
}

/// Apply each compiled rule. Returns the rewritten body and the count
/// of substitutions made.
fn sanitize(input: &str) -> (String, usize) {
    let mut out = input.to_string();
    let mut applied = 0;
    for (regex, replacement, _description) in compiled_rules() {
        let n = regex.find_iter(&out).count();
        if n > 0 {
            out = regex.replace_all(&out, *replacement).into_owned();
            applied += n;
        }
    }
    (out, applied)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a synthetic Slack-webhook-shaped URL from fragments. The full
    /// URL is never present as a source literal — that's deliberate, so
    /// GitHub's secret-scanner doesn't flag the test as a real webhook.
    fn synthetic_slack_url() -> String {
        let prefix = "https://hooks.slack.com/";
        let api = "services/";
        let team = "TXXXXXXXXXX";
        let bot = "BXXXXXXXXXX";
        // 24 lowercase placeholder chars — same shape as a real token, no value.
        let token = "x".repeat(24);
        format!("{prefix}{api}{team}/{bot}/{token}")
    }

    #[test]
    fn sanitize_rewrites_slack_webhook_shape() {
        let url = synthetic_slack_url();
        let input = format!("url: {url}\n");
        let (out, n) = sanitize(&input);
        assert_eq!(n, 1);
        assert!(!out.contains(&url));
        assert!(out.contains("SLACK-WEBHOOK-EXAMPLE"));
    }

    #[test]
    fn sanitize_handles_multiple_occurrences() {
        let input = concat!(
            "a: https://hooks.slack.com/services/TAAA/BAAA/aaaaaaaaaaaaaaaa\n",
            "b: https://hooks.slack.com/services/TBBB/BBBB/bbbbbbbbbbbbbbbb\n",
        );
        let (_, n) = sanitize(input);
        assert_eq!(n, 2);
    }

    #[test]
    fn sanitize_is_a_noop_when_clean() {
        let input = "no secrets here\n";
        let (out, n) = sanitize(input);
        assert_eq!(n, 0);
        assert_eq!(out, input);
    }
}
